"""empty message

Revision ID: 0c86315bfd0c
Revises: ff67d3a6649f
Create Date: 2023-07-31 18:17:20.761683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c86315bfd0c'
down_revision = 'ff67d3a6649f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
